### ISSUE TITLE
Investigate use of BlockKit

### ISSUE THREAD

**Issue by jrsmth** [jrsmth/waffle-bot#22]
https://api.slack.com/block-kit

Definitely worth taking a look

**Comment by haydende** [comment]
JSON Structure for this Framework is already in used with the present function in archbishop.py. We can enhance this with builder classes to make the generation of this JSON easier. This can be achieved with either:
* An in-house solution for bulding these
* Anything already available in the Bolt framework

A decision needs to be made on which of the above is more viable.
