### ISSUE TITLE
Implement configurable vars to scroll functionality

### ISSUE THREAD

**Issue by AdamJ335** [jrsmth/waffle-bot#50]
Pull max scroll amount and minimum streak value into configuration

**Comment by AdamJ335** [comment]
Decision is to set 
LOCAL:
max scroll amount = 2
minimum streak = 1

DEV:
max scroll amount = 3
minimum streak = 2

PROD:
max scroll amount = 3
minimum streak = 2

**Comment by jrsmth** [comment]
Releasing `0.3.1`
