### ISSUE TITLE
Update dethrone Message to announce new king

### ISSUE THREAD

**Issue by AdamJ335** [jrsmth/waffle-bot#52]
E.G
Unlucky James! You are no longer worthy to be king
Your reign lasted 30 days, a mighty feat

The Waffle kingdom must crown a new king.

Where `reign` is replaced with `crusade` on members who are not kings

**Comment by jrsmth** [comment]
Can the poor soul who ends up on this ticket check the dethrone (and subsequent) crown of the new king. Appears to be a bug as of 19th April 2024. 

<img width="626" alt="Screenshot 2024-04-19 at 09 34 32" src="https://github.com/jrsmth/waffle-bot/assets/34093915/86d3fa9f-797c-498f-866b-f0464a528e76">

**Comment by AdamJ335** [comment]
Bug has since been fixed in develop but not in main. Removing bug label as already fixed.
