### ISSUE TITLE
Archbishop does not respond when 'top-text' is included in slack message

### ISSUE THREAD

**Issue by jrsmth** [jrsmth/waffle-bot#57]
## Reproduce
* Post a message in Slack that includes other text, unrelated to the WaffleResult

## Screenshots
<img width="1043" alt="Screenshot 2024-04-26 at 10 41 40" src="https://github.com/jrsmth/waffle-bot/assets/34093915/3589b0a5-3380-4111-9998-d9a1046a1775">

* Post with unrelated text

<img width="1043" alt="Screenshot 2024-04-29 at 10 15 29" src="https://github.com/jrsmth/waffle-bot/assets/34093915/1d39a35d-77a3-47b8-b104-f115ff9d3283">

* Some processing does occur, but no message in Slack (errors somewhere?)

<img width="1038" alt="Screenshot 2024-04-26 at 10 41 49" src="https://github.com/jrsmth/waffle-bot/assets/34093915/0a0fd25b-f230-489f-91e4-78df5f0cc112">

* Data is not updated according to postman

<img width="528" alt="Screenshot 2024-04-26 at 10 42 56" src="https://github.com/jrsmth/waffle-bot/assets/34093915/cbcbada9-72e3-44a5-9c29-229012267ce8">

* Post without unrelated text and see message from the Archbishop as usual

## Considerations
* Does this just apply to 'top-text', or 'bottom-text' as well?

**Comment by haydende** [comment]
The log message we do see is coming from the `/event` endpoint, which is then meant to pass received message to Bolt so it can judge which of the registered handlers should handle it.

If my understanding is correct, it's convinced that a post with a string of text before '#waffleXYZ' doesn't match the conditions for the registered handler.
