### ISSUE TITLE
Archbishop unable to process broken streak

### ISSUE THREAD

**Issue by AdamJ335** [jrsmth/waffle-bot#61]
Waffle game responds with this block when streak breaks:

![image](https://github.com/jrsmth/waffle-bot/assets/76915670/6525a7e0-3d2e-40a6-8b1a-67f11be21458)

We can see that the score is X which breaks into the code block `[handle_waffle] Disregarding event, could not extract waffle data` and returns the method

Need to fix as valid score to process and update

**Comment by jrsmth** [comment]
For completeness, this was accidentally introduced with a recent bug fix (within `0.4.1`), which tightened the specificity of the regular expression condition for messaging handling - i.e it has not been present throughout the whole project.
